# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rentit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rentit
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'Alamofire' 
  pod 'R.swift'
  pod 'SwiftyMenuBar'
  pod 'Cosmos'
end
